export const CONFIG = Object.freeze({
  version: '4.0.0',
  storageKey: 'wae_neon_rider_high_score_v4',
  profileKey: 'wae_neon_rider_profile_v4',
  world: {
    xMin: -16,
    xMax: 16,
    yMin: -9.5,
    yMax: 9.5,
    shipZ: 10,
    spawnZ: -120,
    cullZ: 34,
  },
  ship: {
    speed: 22,
    radius: 1.35,
    shield: 100,
    hitDamage: 28,
    invulnerability: 0.75,
  },
  laser: {
    speed: 96,
    cooldown: 0.15,
    rapidCooldown: 0.07,
    overdriveCooldown: 0.052,
    lifetimeZ: -150,
    radius: 0.62,
  },
  asteroid: {
    baseSpeed: 25,
    minRadius: 0.72,
    maxRadius: 2.35,
    spawnInterval: 0.92,
    minSpawnInterval: 0.33,
  },
  drone: {
    baseSpeed: 19,
    spawnChance: 0.28,
    fireInterval: 1.45,
    bulletSpeed: 30,
    bulletDamage: 18,
    maxActive: 4,
  },
  boss: {
    sectorSeconds: 42,
    baseHp: 36,
    hpPerSector: 14,
    bulletSpeed: 28,
    fireInterval: 0.68,
    reward: 800,
  },
  progression: {
    levelEvery: 500,
    maxSpeedMultiplier: 3.05,
    comboWindow: 2.35,
    maxComboMultiplier: 8,
  },
  heat: {
    max: 100,
    kill: 11,
    droneKill: 18,
    nearMiss: 14,
    decayPerSecond: 5.5,
    overdriveDuration: 6.5,
  },
  powerups: {
    dropChance: 0.16,
    shieldRestore: 30,
    rapidDuration: 7,
  },
  rendering: {
    stars: 1500,
    maxPixelRatio: 2,
  },
});
