import { CONFIG as V4_CONFIG } from '../v4/config.js';

export const SHIPS = Object.freeze({
  falcon: Object.freeze({
    id: 'falcon',
    name: 'FALCON MK-I',
    className: 'INTERCEPTOR',
    cost: 0,
    description: 'Equilibrio total para dominar cualquier sector.',
    speed: 1,
    shield: 1,
    fireRate: 1,
    heatGain: 1,
    accent: 0x22d3ee,
    scale: [1, 1, 1],
  }),
  viper: Object.freeze({
    id: 'viper',
    name: 'VIPER R',
    className: 'ACE RACER',
    cost: 10,
    description: 'Más velocidad y cadencia a cambio de blindaje.',
    speed: 1.18,
    shield: 0.84,
    fireRate: 0.82,
    heatGain: 1.12,
    accent: 0xfacc15,
    scale: [0.9, 0.88, 1.08],
  }),
  aegis: Object.freeze({
    id: 'aegis',
    name: 'AEGIS X',
    className: 'HEAVY GUARD',
    cost: 18,
    description: 'Blindaje de asalto para aguantar combates largos.',
    speed: 0.88,
    shield: 1.38,
    fireRate: 1.08,
    heatGain: 0.94,
    accent: 0x34d399,
    scale: [1.12, 1.08, 1.03],
  }),
  nova: Object.freeze({
    id: 'nova',
    name: 'NOVA PRIME',
    className: 'EXPERIMENTAL',
    cost: 30,
    description: 'Tecnología experimental: movilidad alta y OVERDRIVE acelerado.',
    speed: 1.09,
    shield: 1.02,
    fireRate: 0.9,
    heatGain: 1.38,
    accent: 0xe879f9,
    scale: [1.02, 0.95, 1.12],
  }),
});

export const WEAPONS = Object.freeze({
  pulse: Object.freeze({
    id: 'pulse',
    name: 'PULSE TWIN',
    className: 'DUAL CANNON',
    cost: 0,
    description: 'Doble cañón estable y preciso.',
    lanes: [-3.2, 3.2],
    cooldown: 1,
  }),
  trident: Object.freeze({
    id: 'trident',
    name: 'TRIDENT VX',
    className: 'TRIPLE ARRAY',
    cost: 8,
    description: 'Añade un tercer haz central para barrer líneas frontales.',
    lanes: [-3.2, 0, 3.2],
    cooldown: 1.08,
  }),
  storm: Object.freeze({
    id: 'storm',
    name: 'STORM QUAD',
    className: 'QUAD ARRAY',
    cost: 16,
    description: 'Cuatro líneas de fuego para presión de área.',
    lanes: [-3.2, -1.25, 1.25, 3.2],
    cooldown: 1.16,
  }),
  eclipse: Object.freeze({
    id: 'eclipse',
    name: 'ECLIPSE V',
    className: 'FIVE-LANE ARRAY',
    cost: 28,
    description: 'Matriz de cinco haces. Potencia brutal con cadencia controlada.',
    lanes: [-3.2, -1.6, 0, 1.6, 3.2],
    cooldown: 1.26,
  }),
});

export const CONFIG = Object.freeze({
  ...V4_CONFIG,
  version: '5.0.0',
  profileKey: 'wae_neon_rider_profile_v5',
  legacyProfileKey: V4_CONFIG.profileKey,
  meta: Object.freeze({
    starterShip: 'falcon',
    starterWeapon: 'pulse',
    visibleGalaxyNodes: 7,
  }),
});
